# Generated by Django 5.2.17 on 2026-08-31 11:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='aniversário')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='ingrediente')),
                ('unit', models.CharField(choices=[('g', 'Grama'), ('ml', 'Mililitro'), ('un', 'Unidade')], default='g', max_length=4, verbose_name='unidade')),
                ('package_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='quantidade da embalagem')),
                ('package_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço da embalagem')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque atual')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque mínimo')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='produto')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='peso (g)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço de venda')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade pronta')),
                ('active', models.BooleanField(default=True, verbose_name='disponível na loja')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='receita')),
                ('yield_quantity', models.PositiveIntegerField(default=1, verbose_name='rendimento em unidades')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='custo adicional')),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='acréscimo de custos (%)')),
                ('preparation_minutes', models.PositiveIntegerField(default=0, verbose_name='tempo de preparo (min)')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('CONFIRMADO', 'Confirmado'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], db_index=True, default='NOVO', max_length=20, verbose_name='status')),
                ('delivery_type', models.CharField(choices=[('RETIRADA', 'Retirada'), ('ENTREGA', 'Entrega')], default='RETIRADA', max_length=10, verbose_name='recebimento')),
                ('delivery_address', models.CharField(blank=True, max_length=255, verbose_name='endereço de entrega')),
                ('requested_for', models.DateTimeField(blank=True, null=True, verbose_name='data desejada')),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartão'), ('A_RECEBER', 'Pagar depois')], default='PIX', max_length=15, verbose_name='forma de pagamento')),
                ('payment_status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10, verbose_name='pagamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='taxa de entrega')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='negocio.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor unitário')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negocio.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='negocio.product', verbose_name='produto')),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], db_index=True, default='PENDENTE', max_length=10)),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='data do pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='negocio.customer', verbose_name='cliente')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable', to='negocio.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'conta a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data')),
                ('description', models.CharField(max_length=200, verbose_name='descrição')),
                ('kind', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=8, verbose_name='tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entries', to='negocio.order')),
                ('receivable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_entry', to='negocio.receivable')),
            ],
            options={
                'verbose_name': 'lançamento de caixa',
                'verbose_name_plural': 'lançamentos de caixa',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batches', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='quantidade de receitas')),
                ('units_produced', models.PositiveIntegerField(default=0, verbose_name='unidades produzidas')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('produced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='produzido em')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='negocio.recipe', verbose_name='receita')),
            ],
            options={
                'verbose_name': 'produção',
                'verbose_name_plural': 'produções',
                'ordering': ['-produced_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='negocio.recipe', verbose_name='receita'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('COMPRA', 'Compra/entrada'), ('PRODUCAO', 'Uso em produção'), ('AJUSTE', 'Ajuste')], max_length=12, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade (+ entrada / - saída)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor da movimentação')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='negocio.ingredient', verbose_name='ingrediente')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade utilizada')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='negocio.ingredient', verbose_name='ingrediente')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negocio.recipe', verbose_name='receita')),
            ],
            options={
                'verbose_name': 'item da receita',
                'verbose_name_plural': 'itens da receita',
                'ordering': ['id'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
