# Generated by Django 5.2.17 on 2026-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('RETIRADA', 'Retirada')], default='RETIRADA', max_length=10, verbose_name='recebimento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão')], default='PIX', max_length=15, verbose_name='forma de pagamento'),
        ),
    ]
