# Generated by Django 5.2.17 on 2026-09-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_alter_order_delivery_type_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailablePickupDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(db_index=True, unique=True, verbose_name='data disponível')),
                ('active', models.BooleanField(default=True, verbose_name='disponível para pedidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'data de retirada',
                'verbose_name_plural': 'datas de retirada',
                'ordering': ['pickup_date'],
            },
        ),
    ]
