# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negocio", "0003_availablepickupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_deducted_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="estoque baixado em",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOVO", "Novo"),
                    ("CONFIRMADO", "Aprovado"),
                    ("EM_PREPARO", "Em preparo"),
                    ("PRONTO", "Pronto"),
                    ("CONCLUIDO", "Concluído"),
                    ("CANCELADO", "Cancelado"),
                ],
                db_index=True,
                default="NOVO",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
